patch_generation_ignore_paths:
- .distro
sources:
- path: luksmeta-9.tar.bz2
  url: https://sources.stream.centos.org/sources/rpms/luksmeta/luksmeta-9.tar.bz2/sha512/eeecc3de9d621c380d29b2f2ca6ce715f09c20aac8ffc6a3d3cc7dc30c5dc46df686e61928d0accf7e7281ad9baa6ee59a0cf5b58635a311769d8e08c5cc94bd/luksmeta-9.tar.bz2
specfile_path: .distro/luksmeta.spec
upstream_project_url: git@github.com:TomasTomecek/luksmeta.git
upstream_ref: v9
