language: c
before_script:
  - autoreconf -if
script:
  - ./configure --prefix=/usr
  - make -k check TESTS=
  - if ! sudo make check; then cat ./test-suite.log ; exit 1; fi
compiler:
  - clang
  - gcc
dist: trusty
sudo: required
addons:
  apt:
    packages:
      - libcryptsetup-dev
